name: Build and Push Docker Image to Registry

on:
  push:
    branches:
      - main
      - proxima

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache
      # Configuração específica para Cloudflare Free (limite restrito)
      # Chunks de 512KB para máxima compatibilidade com registries limitados
      DOCKER_UPLOAD_MAX_CHUNK_SIZE: 524288
      # Reduzir paralelismo para evitar rate limiting do Cloudflare
      DOCKER_UPLOAD_MAX_CONCURRENT_UPLOADS: 1
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar metadados da imagem (tags e labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Nome base da imagem (inclui registry e owner)
          images: |
            ${{ secrets.GIT_REGISTRY }}/${{ secrets.GIT_OWNER }}/litellm-pgvector
          tags: |
            type=raw,value=latest
            type=sha,format=short
            type=ref,event=branch

      - name: Login no Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GIT_REGISTRY_USER }}
          password: ${{ secrets.GIT_REGISTRY_PASSWORD }}
          registry: ${{ secrets.GIT_REGISTRY }}

      - name: Habilitar QEMU (multi-arquitetura)
        uses: docker/setup-qemu-action@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir e enviar imagem multi-arch (amd64, arm64)
        uses: docker/build-push-action@v6
        timeout-minutes: 60
        id: docker_build
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Otimizações agressivas para reduzir tamanho
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          # Configurações para upload em registries com limitações severas
          provenance: false
          sbom: false
        env:
          # Configurações específicas para registries limitados
          DOCKER_UPLOAD_CHUNK_SIZE: 524288
          DOCKER_UPLOAD_MAX_CONCURRENT_UPLOADS: 1
          # Timeout mais longo para requests instáveis
          DOCKER_CLIENT_TIMEOUT: 600
          DOCKER_UPLOAD_TIMEOUT: 600
